dotenv: .env

networks:
  default: development
  sepolia:
    ETH_USD_PRICE_FEED: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
  mainnet-fork-dev:
    ETH_USD_PRICE_FEED: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419"
    verify: False
  mainnet-fork:
    ETH_USD_PRICE_FEED: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419"
    verify: False

dependencies:
  # - organization/repo@version
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"